:seedling: TK-4939 Preflight Plugin : Add Support for Pod Scheduling
trilioData/tvk-plugins pull request #112
Opened 2022-03-03 10:38 UTC by prasad-trilio

Added support for scheduling of preflight pods.

One CLI flag added - `node-selector` - Allows user to input multiple labels for node selection to schedule pods on a particular set of nodes.

Pod scheduling supports node selection, pod affinity/anti-affinity, node affinity and taints and tolerations.
Except node-selector flag other pod scheduling options currently do not have CLI flag support. Input for these pod scheduling options must be given through the config file.
This is because there are a lot of options to specify in affinity and tolerations. Hence, input only through config file is supported.

2022-03-09 13:08 UTC, msurudwad requested changes
- Remove `nolint` from `tests/preflight/test_helper.go` and fix lint failures

2022-03-09 13:08 UTC, msurudwad commented on tests/preflight/preflight_test.go
> +					node.Spec.Taints = nodeTaints
do not add taints .. for this CI node, it'll stop scheduling pods of all CI jobs

2022-03-09 13:08 UTC, msurudwad commented on tests/preflight/preflight_test.go
> +			Context("Preflight run command, taints and tolerations test cases with pods able to schedule on node of a cluster", func() {
For now, comment taint related all `Context`. We cannot add taints on CI nodes.

2022-03-10 05:58 UTC, prasad-trilio commented on tools/preflight/cleanup.go
> +	CleanupMode string `json:"cleanupMode"`
Yes branch was rebased.

2022-03-10 07:18 UTC, prasad-trilio commented on tests/preflight/preflight_test.go
> +						Expect(err).To(BeNil())
Setting same labels multiple times on a node, does not give error. Hence, won't be a problem in parallel CI runs.

2022-03-14 06:04 UTC, msurudwad approved these changes

2022-03-14 06:07 UTC, msurudwad commented on cmd/preflight/cmd/cleanup.go
> +  kubectl tvk-preflight cleanup --uid <preflight Run uid> --log-level <log-level>
revert this

2022-03-14 06:10 UTC, merged