:sparkles: TK-5683 Add env tests for DNS resolution and volume snapshot
trilioData/tvk-plugins pull request #145
Opened 2022-05-06 09:20 UTC by prasad-trilio

Added env tests for DNS and volume snapshot subroutines wherever possible.

2022-05-22 19:38 UTC, msurudwad requested changes

2022-05-22 19:38 UTC, msurudwad commented on tools/preflight/preflight_test.go
> +				unstructPod := &unstructured.Unstructured{}
use concrete type like `corev1.Pod{}` then validation pod's field will be easy .. do this wherever applicable.

2022-05-22 19:38 UTC, msurudwad commented on tools/preflight/preflight_test.go
> +						pod, testErr = runOps.createSourcePodFromPVC(ctx, nameSuffix, pvcName, testClient.ClientSet)
move this inside `It` of whichever test requiring this. Function under test should be written & called from `It`.

2022-05-22 19:38 UTC, msurudwad commented on tools/preflight/preflight_test.go
> +			It("Should create source pod from pvc in bound state", func() {
call `runOps.createSourcePodFromPVC` from this test-case, otherwise it is just testing `RuntimeClient` func.

2022-05-22 19:38 UTC, msurudwad commented on tools/preflight/preflight_test.go
> +			})
these 3 tests can be clubbed together and written as single `It`

2022-05-22 19:38 UTC, msurudwad commented on tools/preflight/preflight_test.go
> +				}()
go routine not needed here

2022-05-22 19:38 UTC, msurudwad commented on tools/preflight/preflight_test.go
> +					_, err := runOps.createRestorePodFromSnapshot(ctx, volSnap, testPVC, podKey.Name, testNameSuffix, testClient.ClientSet)
move this to `It`

2022-05-22 19:38 UTC, msurudwad commented on tools/preflight/preflight_test.go
> +			go func() {
go routine not needed.. do this wherever applicable

2022-05-31 10:05 UTC, msurudwad requested changes

2022-06-01 06:42 UTC, prasad-trilio commented on tools/preflight/preflight.go
> +		return nil
Changes for preflight resources created in other checks such as volume-snapshot will also need to be handled. Will do this in a separate ticket

2022-06-01 09:12 UTC, merged