:seedling: TK-2103 : Added Test Cases for Preflight Script
trilioData/tvk-plugins pull request #5
Opened 2021-03-08 20:06 UTC by pallav-trilio

2021-03-12 12:25 UTC, msurudwad requested changes
Update Run Preflight Integration Tests step of preflight job to run shell test-suite.

2021-03-12 12:25 UTC, msurudwad commented on tests/preflight/shunit2
> +# $Id: shunit2 335 2011-05-01 20:10:33Z kate.ward@forestent.com $
remove author and license info

2021-03-13 17:24 UTC, msurudwad commented
> Update Run Preflight Integration Tests step of preflight job to run shell test-suite.

Address this review comment in this PR as well… this way we'll know if test-cases are passing or not. 

Make sure shell lint passes and all jobs passes too in order to approve this PR.

2021-03-16 17:18 UTC, msurudwad requested changes
1. Randomize `dnsutils` pod name as well, in preflight script. Also, check for other resources which are using hardcoded name.
2. How are you taking care of cleaning up of residual resources created from tests, if test-cases fail?

2021-03-17 06:47 UTC, msurudwad requested changes
Resolve review comments… otherwise LGTM

2021-03-17 06:47 UTC, msurudwad commented on tests/preflight/preflight_test.sh
> +set -o errexit
set this at start of script

2021-03-17 06:47 UTC, msurudwad commented on tests/preflight/preflight_test.sh
> +set -o pipefail
set this at start of script

2021-03-18 06:29 UTC, pallav-trilio commented on tests/preflight/preflight_test.sh
> +set -o errexit
resolved

2021-03-18 06:29 UTC, pallav-trilio commented on tests/preflight/preflight_test.sh
> +set -o pipefail
resolved

2021-03-18 08:46 UTC, madhurtrilio approved these changes

2021-03-18 08:46 UTC, merged