:book: Update target browser docs
trilioData/tvk-plugins pull request #93
Opened 2021-11-25 11:18 UTC by pankaj9310

2021-11-26 17:46 UTC, msurudwad requested changes

2021-11-26 17:46 UTC, msurudwad commented on docs/target-browser/README.md
> +target-browser's `/backupplan`, `/backup` and `/metadata` API.
add other APIs which are missing - `resource-metadata`, etc

2021-11-26 17:46 UTC, msurudwad commented on docs/target-browser/README.md
> +  kubectl tvk-target-browser get metadata --backup-uid <uid> --backup-plan-uid <uid> --target-name <name> --target-namespace <namespace> --use-https true --certificate-authority <certificate-path>
for boolean flag, no need to pass values `true/false`.. simply flag name is sufficient that will be treated as `true` and if flag is not provided that will be `false`.

2021-12-01 11:42 UTC, msurudwad approved these changes
LGTM

2021-12-01 11:48 UTC, madhurtrilio approved these changes

2021-12-01 11:48 UTC, merged